config/routes.rb
Rails.application.routes.draw do

  root 'home#show'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#delete"
  get "/dashboard", to: "home#show"

  resources :users, only: [:new, :create, :show]
  namespace :api do
    namespace :v1 do
      resources :links, only: [:index, :show, :create, :update, :destroy], defaults: { format: :json }
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :title, :url, :user_id, presence: true
  default_scope -> { order(id: :desc) }
  enum read: [:unread, :read]
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email_address, :password_digest, presence: true
  has_secure_password
  has_many :links
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  respond_to :json

  def index
    respond_with current_user.links
  end

  def create
    if valid(params[:url])
      respond_with current_user.links.create(link_params), location: nil
    end
  end

  def update
    respond_with current_user.links.update(params[:id], link_params)
  end

  def destroy
    respond_with current_user.links.delete(params[:id]), nil
  end

  private

  def link_params
    params.permit(:title, :url, :read)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  require 'uri'

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def valid(url)
    uri = URI.parse(url)
    uri.kind_of?(URI::HTTP)
    rescue URI::InvalidURIError
    false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email_address(params[:session][:email_address])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:error] = "Invalid login credentials"
      render :new
    end
  end

  def delete
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @new_user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:email_address] = @user.email_address
      flash[:notice] = "Account Created!"
      redirect_to login_path
    else
      flash[:notice] = "Invalid user credentials. Please try again."
      redirect_to login_path
    end
  end

  def dashboard
    @user = User.find(session[:user_id])
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password)
  end
end

app/views/home/_loggedIn.html.erb
<div class="container center">
  <div class="row">
    <div class="col s12 m4 l2"><p></p></div>
    <div class="col s12 m4 l8">
    <div class="input-field">
      <input id="link-title" type="text" class="validate">
      <label>Title</label>
    </div>
    <div class="input-field">
      <input id="link-url" type="text" class="validate">
      <label>URL</label>
    </div>
    <div class="input-field">
      <button class="btn waves-effect waves-light submit-button" id="create-link" type="submit" name="action">Create</button>
    </div>
    <p></p></div>
    <div class="col s12 m4 l2"><p></p></div>
  </div>
  <br>
    <div class="col s12"><span class="flow-text"><h4>Link Index</h4></span></div>
    <nav>
      <div class="nav-wrapper">
        <form>
          <div class="input-field white">
            <div class="ui-widget">
              <input id="link-search" type="search" required>
            </div>
          </div>
        </form>
      </div>
    </nav>
    <br>
    <div class="col s12"><span class="light italic">(click title or url to edit, press enter to save)</span></div>
  <table class="centered">
    <br><br>
    <div class="col s12" id="link-index"></div>
  </table>
  </div>
</div>

app/views/home/_notLoggedIn.html.erb
<div class="container center">
  <br>
  <br>
  <h2>Welcome to Thought Central</h2>
  <br>
  <h4><%= link_to "Login", login_path %> or <%= link_to "Sign Up", new_user_path %></h4>
</div>

app/views/home/show.html.erb
<% if current_user %>
  <%= render partial: "loggedIn" %>
<% else %>
  <%= render partial: "notLoggedIn" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughtbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>
</head>
  <main>
  <body>
    <header>
      <nav class="z-depth-0 navbar">
        <div class="nav-wrapper blue-grey lighten-1">
          <a href="/" class="brand-logo black-text center" id="navbar-branding">Thoughtbox</a>
          <ul id="nav-mobile black-text" class="right hide-on-med-and-down">
            <% if current_user %>
              <li><%= link_to "Logout", logout_path %> </li>
            <% else %>
              <li><%= link_to "Login", login_path %> </li>
              <li><%= link_to "Sign Up", new_user_path %> </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <br>
    <% flash.each do |type, msg| %>
        <%= content_tag :div, sanitize(msg), class: " flash flash_#{type}" %>
    <% end %>
    <br>
    <div class="container">
      <%= yield %>
    </div>
    <br>
    </main>​
    <footer class="page-footer blue-grey lighten-1">
      <div class="footer-copyright">
        <div class="container">
          <a class="black-text text-lighten-4 left" href="https://github.com/acareaga" target="_blank">Made by Aaron Careaga</a>
          <div class= "black-text text-lighten-4 right">© 2016 Thoughtbox</div>
        </div>
      </div>
    </footer>
  </body>
</body>
</html>

app/views/users/new.html.erb
<div class="container">
  <h3>Sign Up</h3>
  <br><br>
  <%= form_for(:user, url: users_path) do |f| %>
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.label :confirm_password %><br>
    <%= f.password_field :password %><br>
    <%= f.button "Create" %>
  <% end %>
</div>